### ISSUE TITLE
Error reading caom XML with missing keywords

### ISSUE THREAD

**Issue by dr-rodriguez** [opencadc/caom2tools#39]
When attempting to read a CAOM2.3 xml with ObservationReader, this line fails due to missing keywords elements. Since keywords are optional, this line should only run if `keywords_element` is not None. 

https://github.com/opencadc/caom2tools/blob/416afc51c4cd3e02d7f493ea9de42b9c51805094/caom2/caom2/obs_reader_writer.py#L264

**Comment by andamian** [comment]
Ha! We also run into it and I was in the middle of releasing the patch. Fixed and released in caom2-2.3.0a5.
