### ISSUE TITLE
'dimension' in CoordFunction2D misnamed?

### ISSUE THREAD

**Issue by hjeeves** [opencadc/caom2tools#59]
By the CAOM2 data model, shouldn't it be called 'naxis' so it's symmetric with the data model?

**Comment by yeunga** [comment]
The CoordFunction2D in wcs.py in version 2.3.7 of caom2tools/caom2 uses 'dimension' which agrees with the CAOM2 data model. So there is no apparent issue.

Spoke with Helena. She could not remember the details. She agreed that there was no issue anymore.
